#!/usr/bin/with-contenv sh

[ -z "${WODBY_HOME}" ] && WODBY_HOME="/srv"
[ -z "${WODBY_CONF}" ] && WODBY_CONF="${WODBY_HOME}/conf"
[ ! -d  "${WODBY_HOME}" ] && mkdir -p "${WODBY_HOME}"
[ ! -d  "${WODBY_CONF}" ] && mkdir -p "${WODBY_CONF}"
[ ! -d "${WODBY_CONF}/redis" ] && mkdir -p "${WODBY_CONF}/redis"

if [ ! -f "${WODBY_CONF}/redis/redis.conf" ] && [ ! -L "/etc/redis.conf" ];then
        mv "/etc/redis.conf" "${WODBY_CONF}/redis/"
        chown -R "${WODBY_USER}":"${WODBY_GROUP}" "${WODBY_CONF}/redis"
        ln -sf "${WODBY_CONF}/redis/redis.conf" "/etc/redis.conf"
elif [ -f "${WODBY_CONF}/redis/redis.conf" ] && [ ! -L "/etc/redis.conf" ];then
        ln -sf "${WODBY_CONF}/redis/redis.conf" "/etc/redis.conf"
fi
